### PR TITLE
Revert "Make MySQL table modifications always use one statement to fix total table-corruption bug #1115"

### PR DESCRIPTION
**Pull request by marcj**
Reverts propelorm/Propel2#1116

Because of https://github.com/propelorm/Propel2/issues/1144 and I discovered some strange effects with migrations after this PR as well, so revert for the moment (`Cannot drop index 'PRIMARY': needed in a foreign key constraint`).

### CODE REVIEW

**Comment by gharlan** [comment]
:+1:

**Comment by ExplodingCabbage** [comment]
Ah, what a pity. Just discovered this revert!

Not sure it's the right call; the bug https://github.com/propelorm/Propel2/pull/1116 fixes corrupts your database, whereas the bug this revert fixes just causes an illegal statement to be generated that will error out when you try to execute it. Still, it would be nice to figure out how to fix both simultaneously.

**Comment by marcj** [comment]
Yes, in my daily use cases where I change a lot of tables during development I had several issues with this PR, so I reverted it. Maybe we get it working without `FOREIGN_KEY_CHECKS=0` so we get always a error messages instead of a corrupt database, however I'm not sure if this is even possible.

**Comment by gharlan** [comment]
> Yes, in my daily use cases where I change a lot of tables during development I had several issues with this PR

Same here

> Still, it would be nice to figure out how to fix both simultaneously.

👍

**Pull request merged**
