### PR TITLE
Speedup travis builds

### PR DESCRIPTION
**Pull request by staabm**
Removing some defaults.. Try to make the travis composer cache work and no longer trigger api limits

### CODE REVIEW

**Comment by staabm** [comment]
I think we could also drop php5.5..  It will be eol in a few months and I guess propel2 will not be released before...

http://php.net/supported-versions.php

**Comment by marcj** [comment]
When it ends and we have no release, we can drop it then :+1:

**Comment by staabm** [comment]
Ok, ready to land then

**Comment by marcj** [comment]
Perfect, let us wait until travis is green again and mariadb is fixed, then I'm going to merge this :+1:

**Pull request merged**
