### PR TITLE
Compobility with php 7.2 and strict type

### PR DESCRIPTION
**Pull request by Big-Shark**
>Warning: count(): Parameter must be an array or an object that implements Countable
```
if (count($pk = $value->getPrimaryKey()) > 1 || is_object($value->getPrimaryKey())) {
```
If $value->getPrimaryKey() return int

### CODE REVIEW

**Comment by Big-Shark** [comment]
Duplicate #1425, issue #1424

**Comment by Big-Shark** [comment]
@marcj Please, fix compatibility with php7.2)

**Comment by kije** [comment]
+1

**Comment by marcj** [comment]
Already fixed, sorry for the delay!

**Pull request closed without merging**
