### PR TITLE
'Complex count': COUNT(*) => SQL_CALC_FOUND_ROWS

### PR DESCRIPTION
**Pull request by jadbaz**
This is not a 'better' method in general, it's just one that I have found to be faster for most cases.
It's also not an extremely clean method as I'm using a string manipulation and using 2 consecutive queries.

The problem with subselects (anything in the form of SELECT  FROM (sql)) is that it is not optimized in MYSQL. Do it on a large dataset and compare it to a single select. The more subselects, the slower the query.
On 3300 rows having 40 columns, mysql 5.1.73:
_Old method: between 1 and 8 seconds (No idea why so inconsistent).
_New method: between 0.6 and 1.1 seconds consistently

### CODE REVIEW

**Comment by jadbaz** [comment]
The failing check has to do with the expectation of SELECT COUNT(*). SELECT FOUND_ROWS() found instead.
This is the expected behaviour of this check.
Still needs to be considered

**Comment by angelk** [comment]
IMO SQL_CALC_FOUND_ROWS  is [not always faster](http://stackoverflow.com/questions/186588/which-is-fastest-select-sql-calc-found-rows-from-table-or-select-count/188682#188682)

**Comment by asmarovydlo** [comment]
Hello, `SQL_CALC_FOUND_ROWS`  is deprecated in MYSQL since `8.0.17` https://dev.mysql.com/doc/refman/8.0/en/information-functions.html#function_found-rows 

I think we can close the PR

**Comment by gechetspr** [comment]
Is outdated

**Pull request closed without merging**
