### PR TITLE
Readadd model_path to propel bundle.

### PR DESCRIPTION
**Pull request by thomaschaaf**
Unfortunately the PropelConfiguration is used in the Symfony PropelBundle when executing: ```php app/console propel:model:build``` thus this is a quick fix until this is changed in the PropelBundle

### CODE REVIEW

**Comment by marcj** [comment]
Ok, I wait for PropelBundle @havvg

**Comment by havvg** [comment]
Done @marcj

**Comment by marcj** [comment]
Thanks @havvg! Let's see what travis is saying in few minutes :)

**Comment by staabm** [comment]
I guess this change triggers some of the failing tests in the agnostic build, see https://travis-ci.org/propelorm/Propel2/jobs/119884530

@thomaschaaf could you check that?

**Comment by thomaschaaf** [comment]
I fixed it in https://github.com/propelorm/Propel2/pull/1158

**Comment by Big-Shark** [comment]
@thomaschaaf  @marcj Please update documentation

**Comment by thomaschaaf** [comment]
Done https://github.com/propelorm/propelorm.github.com/pull/374

**Pull request merged**
