### PR TITLE
Remove is_resource() as this will always be false in PHP 8

### PR DESCRIPTION
**Pull request by dereuromark**
See PHP8 on resource to object changes

This requires verification if this still works fine for both PHP 7 and 8.

Refs https://github.com/spryker/code-sniffer/pull/228

### CODE REVIEW

**Comment by dereuromark** [comment]
Does anyone of the community here have ideas on how to tackle this?
We  should start preparing some of the next releases here already in a way that PHP8 won't be a big BC break again end of this year.

**Comment by dereuromark** [comment]
@gechetspr This doesn't work, we need a fix here that works for PHP7 and 8 somehow.
Maybe this requires a larger refactor so that we don't have to check the type but can rely on it being a resource?

**Comment by dereuromark** [comment]
@propelorm/propel2 Does anyone have an idea on how to solve this PHP 8 blocker?

**Comment by staabm** [comment]
@dereuromark not sure what the actual problem is.. what is different in PHP8? whats the actual change in php8 which triggers a problem here?

**Comment by dereuromark** [comment]
In PHP8 resources are objects, so that check will never work (always returns false).

**Comment by staabm** [comment]
Most of the mentioned code see to work on streams which IMO are still resources.

Do you have a concrete use-case which no longer works?

**Comment by dereuromark** [comment]
It is possible that with the latest PHP releases they shimmed it back in a way, that we can keep the current method.
If that's the case, great.

Then we just need to solve the other more problematic PHP 8 incompatibilities (mainly around typehints).

**Comment by dereuromark** [comment]
I will close this then for now in favor of linking to https://github.com/propelorm/Propel2/issues/1568
And we will see how we can progress from there.

**Pull request closed without merging**
