### PR TITLE
I18n port

### PR DESCRIPTION
**Pull request by cristianoc72**
Port I18n behavior to the new data mapper architecture.

Notice: I've marked skipped two tests of ConcreteInheritance behavior. With the one-to-many implementation, it seems that the event dispatcher causes an abnormal loop somewhere. I can't fix it by now.

### CODE REVIEW

**Comment by marcj** [comment]
Very nice! Unfortunately I cannot auto merge this pull request :( Can you rebase it please?

**Comment by cristianoc72** [comment]
Sorry, I forgot to rebase before pushing.

**Comment by marcj** [comment]
Very cool, love all those little components building the greater class :)

**Comment by cristianoc72** [comment]
Me too! And Nested set behavior is even better (next PR :smile: ).

**Comment by staabm** [comment]
:tada:

**Comment by marcj** [comment]
Can't wait to see it :)

**Pull request merged**
