### PR TITLE
Fix model_paths unit tests

### PR DESCRIPTION
**Pull request by thomaschaaf**
Fix unit tests that were broken by: https://github.com/propelorm/Propel2/pull/1125

### CODE REVIEW

**Comment by thomaschaaf** [comment]
Sorry for the many commits :( I was on the run but I think everything is fixed now.

**Comment by staabm** [comment]
no hurry, thx for the PR. looks good to me so far. the remaining failing build seems to be mariadb 10.1 related and should be fixed by a separate PR (not related to your initial fix).

**Comment by marcj** [comment]
Yeah, thanks @thomaschaaf! We should nonetheless get rid of those commit messages :)

**Comment by thomaschaaf** [comment]
You can use the new github squish feature :P

Marc J. Schmidt <notifications@github.com> schrieb am Mo., 4. Apr. 2016,
11:13:

**Comment by staabm** [comment]
@marcj I guess you could squash this together using the new github feature

**Comment by staabm** [comment]
contacted travis regarding the mariadb10.1 build, see https://twitter.com/markusstaab/status/716917925064650752

**Comment by marcj** [comment]
Isn't that feature for the guy that creates the pull-request? :P I don't have that new awesome button here.

screen shot 2016-04-04 at 11 37 45

**Comment by staabm** [comment]
@marcj nope that, button is for the people with merge permissions.
see https://github.com/blog/2141-squash-your-commits for details.

maybe you need to configure something in the admin-settings of this repo or it is a github bug.

**Comment by gharlan** [comment]
@marcj you have to click on "Merge pull request" and in the next step you can choose to squash the commits.

**Comment by thomaschaaf** [comment]
@marcj Merging is now a two step process. When you click on the button you are asked how you would like to merge the changes.

**Comment by marcj** [comment]
Awesome, thanks guys :)

**Pull request merged**
