### PR TITLE
Improve ObjectCollection coverage

### PR DESCRIPTION
**Pull request by SofHad**
Additional test to cover: https://github.com/propelorm/Propel2/blob/master/src/Propel/Runtime/Collection/ObjectCollection.php#L270-272

### CODE REVIEW

**Comment by marcj** [comment]
Does this have a reason?

**Comment by SofHad** [comment]
Just to increase covered code.

**Comment by marcj** [comment]
Here again, merge conflicts. Also please squash your commits :)

**Comment by SofHad** [comment]
@marcj 
it's done

**Comment by marcj** [comment]
Thanks :)

**Pull request merged**
