### PR TITLE
External attribute added

### PR DESCRIPTION
**Pull request by SCIF**
Implemented handled of new schema.xml attribute «external» which force to skip marked table on `migration:diff` action.

### CODE REVIEW

**Comment by marcj** [comment]
I'd rather want to see this through "--skip-table" option.

**Comment by SCIF** [comment]
Explain please your point. I suggest mark tables in schema as skipped. How it's to --skip-tables option??

**Comment by marcj** [comment]
schema.xml is the wrong place to put this information at. Better is to place it in the config.yml or pass those information as command option as stated `skip-tables`, which already exists.

**Comment by SCIF** [comment]
Do you mean to add [here](http://propelorm.org/documentation/reference/configuration-file.html#database-settings) something like:
```yaml
skipped_tables:
  - table1
  - table2
```

**Comment by marcj** [comment]
:+1:

**Comment by SCIF** [comment]
Migration diff implemented.

**Comment by marcj** [comment]
very nice :+1:

**Comment by marcj** [comment]
Looks very good, thanks @SCIF, good work!

**Pull request merged**
