### PR TITLE
Address failed tests after applying fix for issue #1425

### PR DESCRIPTION
**Pull request by Gomes81**
Address failed tests after applying fix for issue #1425 which is ralated to the countable issue in php 7.2.

I think the issue is related to the fact that the fix added the condition: is_numeric($pk) && $pk > 1 to the if, which is not present in the previous releases, which then caused some tests to start failing.

### CODE REVIEW

**Comment by dereuromark** [comment]
The php7.2+ compatibility becomes a bit of a critical issue lately as a lot of service providers are rolling out already 7.2 as their default PHP env, and people expect PHP applications to be running on those just fine.

**Comment by Gomes81** [comment]
It seems that the issue was already solved by another commit and this fix is not needed anymore... However, I still prefer this implementation to the one currently implemented.

**Comment by dereuromark** [comment]
What commit/fix do you refer to? You got the example to compare to your solution?

**Comment by Gomes81** [comment]
Sorry for not mention it @dereuromark, it was by this pull request: #1452 (which in fact did such a good job, fixing all the issues with tests in 7.2)

**Comment by marcj** [comment]
Thanks!

**Pull request merged**
