### PR TITLE
Refs #804 - Added ConstantNameTest, modified QuickBuilder to supress inc...

### PR DESCRIPTION
**Pull request by acim**
Test regarding issue #804.

### CODE REVIEW

**Comment by marcj** [comment]
Would you mind squashing/rebasing your commits?

**Comment by acim** [comment]
Of course, it will be fixed during the weekend :)

**Comment by acim** [comment]
Sorry, it took me month and a half to find free time to do this. The tests are failing for the same reason as in the upstream master branch, so nothing regarding my modifications. This is ready to me merged I hope.

**Comment by acim** [comment]
It's green now ;)

**Comment by marcj** [comment]
Cool, thanks :+1: :)

**Pull request merged**
