### PR TITLE
Added phpunit .sh files

### PR DESCRIPTION
**Pull request by Big-Shark**
#1039

### CODE REVIEW

**Comment by Big-Shark** [comment]
@marcj Travis not running, please enable travis hook

**Comment by nymo** [comment]
What about the setup.sqlite.sh file? Shouldn't this be added, too?

**Comment by Big-Shark** [comment]
@nymo No, it does not work)

**Comment by nymo** [comment]
allright thanks for the info :)

**Comment by Big-Shark** [comment]
#1059

**Pull request closed without merging**
