### PR TITLE
Alter comparison so that an int(-1) value for getLimit() evaluates correctly

### PR DESCRIPTION
**Pull request by EVILoptimist**
Simple fix for #960. This one-liner updates this comparison to be consistent with other comparisons for this method.

### CODE REVIEW

**Comment by SCIF** [comment]
Wow, so curious test failure. Leap second effect or just slow data insertion to db? Seems interesting.

**Comment by staabm** [comment]
Any chanche to add a unit test supporting the change?

**Comment by EVILoptimist** [comment]
Ohhh..... Hahaha.... Good idea. Yeah. Lemme take a look :)

**Comment by EVILoptimist** [comment]
Copied the block from the /Propel/Runtime/ActiveQuery/Criteria class. Seems more complete and includes the fix I proposed.

**Comment by EVILoptimist** [comment]
Wrote a test to count() a table. If it executes anything but a simple count query, test will fail.

**Comment by staabm** [comment]
Looks good to me thx. :+1:

**Comment by marcj** [comment]
Very nice, thanks @EVILoptimist!

**Pull request merged**
