### PR TITLE
Migration: Missing "AFTER"/"FIRST" when adding columns (MySQL)

### PR DESCRIPTION
**Pull request by IceShack**
- Copied code from Propel 1
- Changed methods, so the statements can get merged

### CODE REVIEW

**Comment by marcj** [comment]
Thanks, looks pretty good :)

**Comment by gharlan** [comment]
:+1: thanks!

**Comment by robin850** [comment]
It looks like the test suite isn't covering the case with `FIRST`, no ?

**Comment by IceShack** [comment]
@robin850 
Added a unit test for that. #909

**Pull request merged**
