### PR TITLE
custom connections options for slaves

### PR DESCRIPTION
**Pull request by jeremydenoun**
fix behavior described in : https://github.com/propelorm/Propel2/issues/920

### CODE REVIEW

**Comment by marcj** [comment]
Well, actually this won't fix anything as those config values are not read by our service container or PropelBundle. A better approch is to do it the way PropelBundle handles it: It merges the user/password values into the slave array, so master=slave credentials. https://github.com/propelorm/PropelBundle/blob/2.0/PropelBundle.php#L72

**Comment by jeremydenoun** [comment]
I check source code especially :
https://github.com/propelorm/Propel2/blob/master/src/Propel/Runtime/Connection/ConnectionManagerMasterSlave.php#L172

you use complete slave read configuration

your proposal is good but : 
- rarely slaves connection can have different login/password than master (and we can't force them in dsn)
- sometimes we can want specific "options/queries" for slaves database init and finally for profiling and stats we can use another Connection classname

so I think 2 approach are necessary 

Best

**Comment by marcj** [comment]
Mh, then we should not mark those values as required. If they are not defined, they should be taken from the master connection. So, make your newly added options optional and merge those values if they are not defined with the master connection, then I'm ok with it and it addresses all issues. :)

**Comment by jeremydenoun** [comment]
done in 96bac07

**Comment by jeremydenoun** [comment]
I close this pull request because this is linked to my master branch... I will open another only with slave patch... FYI, I improve timestampable behavior and remove Symfony Legacy Validator (throw notice) in my branch

**Pull request closed without merging**
